package dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table ad_city.
*/
public class AdModelDao extends AbstractDao<AdModel, Long> {

    public static final String TABLENAME = "ad_city";

    /**
     * Properties of entity AdModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CityId = new Property(1, Integer.class, "cityId", false, "CITY_ID");
        public final static Property DisplayMode = new Property(2, Integer.class, "displayMode", false, "DISPLAY_MODE");
        public final static Property DisplayTime = new Property(3, Integer.class, "displayTime", false, "DISPLAY_TIME");
        public final static Property ImageUrl = new Property(4, String.class, "imageUrl", false, "IMAGE_URL");
        public final static Property StartTime = new Property(5, String.class, "startTime", false, "START_TIME");
        public final static Property EndTime = new Property(6, String.class, "endTime", false, "END_TIME");
    };


    public AdModelDao(DaoConfig config) {
        super(config);
    }
    
    public AdModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ad_city' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'CITY_ID' INTEGER UNIQUE ," + // 1: cityId
                "'DISPLAY_MODE' INTEGER," + // 2: displayMode
                "'DISPLAY_TIME' INTEGER," + // 3: displayTime
                "'IMAGE_URL' TEXT," + // 4: imageUrl
                "'START_TIME' TEXT," + // 5: startTime
                "'END_TIME' TEXT);"); // 6: endTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ad_city'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AdModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer cityId = entity.getCityId();
        if (cityId != null) {
            stmt.bindLong(2, cityId);
        }
 
        Integer displayMode = entity.getDisplayMode();
        if (displayMode != null) {
            stmt.bindLong(3, displayMode);
        }
 
        Integer displayTime = entity.getDisplayTime();
        if (displayTime != null) {
            stmt.bindLong(4, displayTime);
        }
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(5, imageUrl);
        }
 
        String startTime = entity.getStartTime();
        if (startTime != null) {
            stmt.bindString(6, startTime);
        }
 
        String endTime = entity.getEndTime();
        if (endTime != null) {
            stmt.bindString(7, endTime);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AdModel readEntity(Cursor cursor, int offset) {
        AdModel entity = new AdModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // cityId
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // displayMode
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // displayTime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // imageUrl
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // startTime
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // endTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AdModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCityId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setDisplayMode(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setDisplayTime(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setImageUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setStartTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setEndTime(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(AdModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AdModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
