package dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table bottom_bar.
 */
public class BottomBarItem {

    private Long id;
    private String name;
    private String mouseOutIcon;
    private String mouseOnIcon;
    private String mouseOutColor;
    private String mouseOnColor;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BottomBarItem() {
    }

    public BottomBarItem(Long id) {
        this.id = id;
    }

    public BottomBarItem(Long id, String name, String mouseOutIcon, String mouseOnIcon, String mouseOutColor, String mouseOnColor) {
        this.id = id;
        this.name = name;
        this.mouseOutIcon = mouseOutIcon;
        this.mouseOnIcon = mouseOnIcon;
        this.mouseOutColor = mouseOutColor;
        this.mouseOnColor = mouseOnColor;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMouseOutIcon() {
        return mouseOutIcon;
    }

    public void setMouseOutIcon(String mouseOutIcon) {
        this.mouseOutIcon = mouseOutIcon;
    }

    public String getMouseOnIcon() {
        return mouseOnIcon;
    }

    public void setMouseOnIcon(String mouseOnIcon) {
        this.mouseOnIcon = mouseOnIcon;
    }

    public String getMouseOutColor() {
        return mouseOutColor;
    }

    public void setMouseOutColor(String mouseOutColor) {
        this.mouseOutColor = mouseOutColor;
    }

    public String getMouseOnColor() {
        return mouseOnColor;
    }

    public void setMouseOnColor(String mouseOnColor) {
        this.mouseOnColor = mouseOnColor;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
