package dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here


// KEEP INCLUDES END

import com.jaryjun.common_base.model.Coordinate;

/**
 * Entity mapped to table SEARCH_HISTORY_ITEM.
 */
public class SearchHistoryItem {

    private Long id;
    private Integer city_id;
    private Integer plate_id;
    private Integer type;
    private Integer showId;
    private Integer bizType;
    private String title;
    private String sub_title;
    private Double lat;
    private Double lon;
    private Float level;
    private Integer searchType;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SearchHistoryItem() {
    }

    public SearchHistoryItem(Long id) {
        this.id = id;
    }

    public SearchHistoryItem(Long id, Integer city_id, Integer plate_id, Integer type, Integer showId, Integer bizType, String title, String sub_title, Double lat, Double lon, Float level, Integer searchType) {
        this.id = id;
        this.city_id = city_id;
        this.plate_id = plate_id;
        this.type = type;
        this.showId = showId;
        this.bizType = bizType;
        this.title = title;
        this.sub_title = sub_title;
        this.lat = lat;
        this.lon = lon;
        this.level = level;
        this.searchType = searchType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCity_id() {
        return city_id;
    }

    public void setCity_id(Integer city_id) {
        this.city_id = city_id;
    }

    public Integer getPlate_id() {
        return plate_id;
    }

    public void setPlate_id(Integer plate_id) {
        this.plate_id = plate_id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getShowId() {
        return showId;
    }

    public void setShowId(Integer showId) {
        this.showId = showId;
    }

    public Integer getBizType() {
        return bizType;
    }

    public void setBizType(Integer bizType) {
        this.bizType = bizType;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSub_title() {
        return sub_title;
    }

    public void setSub_title(String sub_title) {
        this.sub_title = sub_title;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLon() {
        return lon;
    }

    public void setLon(Double lon) {
        this.lon = lon;
    }

    public Float getLevel() {
        return level;
    }

    public void setLevel(Float level) {
        this.level = level;
    }

    public Integer getSearchType() {
        return searchType;
    }

    public void setSearchType(Integer searchType) {
        this.searchType = searchType;
    }

    // KEEP METHODS - put your custom methods here
    public boolean isCoordinateOk() {
        Coordinate coordinate = new Coordinate(getLat(), getLon());
        return coordinate.isValidCoordinate();
    }

    /***
     * 是否是地铁线路
     *
     * @return boolean
     */
    public boolean isMetroLine() {
        return getType() == 3;
    }
    // KEEP METHODS END

}
